services:
  abu-maryam-tv:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SITE_URL: "https://abou-maryam.com"
        NEXT_PUBLIC_API_BASE_URL: ""
    image: abu-maryam-tv
    container_name: abu-maryam-tv
    restart: unless-stopped
    env_file:
      - .env.production
    networks:
      - shaolin_web

networks:
  shaolin_web:
    external: true
